account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name = 'logout'),
    path('signup/', signup_view, name = 'signup' ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('account/', include('account.urls')),
     path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import *

app_name = 'pages'

urlpatterns = [
    path('', index, name = 'index'),
    path('post/<int:pk>', single_post, name = 'single_post'),
    path('about/' , about, name = 'about'),
    path('contact/', contact, name = 'contact'),
    path('category/<str:category>/', category, name = 'category'),
    path('search/', search, name = 'search'),
    path('author/<str:author>/', index, name = 'author'),
    path('tag/<str:tag_name>/', index, name = 'tag'),
]

account/models.py
from django.db import models

pages/models.py
from django.db import models
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField



class Author(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']


class Category(models.Model):
    name = models.CharField(max_length=150)


    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']

        

class Post(models.Model):
    title = models.CharField(max_length=350)
    description = models.TextField()
    image = models.ImageField(upload_to='media', null=True, blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)
    tag = TaggableManager()
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(null=True, blank=True)


    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-published_date']


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=150)
    subject = models.CharField(max_length=200)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-created_date']


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=150)
    message = models.TextField()
    is_approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-created_date']

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class CreatUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CustomAuthenticationForm(AuthenticationForm):
    email = forms.EmailField(required=True)

pages/forms.py
from django import forms
from .models import *

class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = '__all__'


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['name', 'email', 'message']

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import CreatUserForm, CustomAuthenticationForm
from django.contrib import messages

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Username or Password is wrong')
    return render(request, 'login.html')

def logout_view(request):
    logout(request)
    return redirect('/')

def signup_view(request):
    form  = CreatUserForm()

    if request.method == 'POST':
        form = CreatUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created successfully for ' + user)
            return redirect('account:login')
        else:
            messages.error(request, 'Plase fill in all fields')
    context = {'form':form}
    return render(request, 'signup.html', context)

pages/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .forms import *
from django.contrib import messages

def index(request, author=None, tag_name=None):
    posts = Post.objects.filter(status=True)
    categories = Category.objects.all()
    if author:
        posts = posts.filter(author__name = author)
    if tag_name:
        posts = posts.filter(tag__name = tag_name)
    
    posts = Paginator(posts, 3)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    context = {'posts':posts, 'categories':categories}
    return render(request, 'index.html', context)


def single_post(request,pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            messages.success(request, 'Your comment has been sent successfully!')
        else:
            messages.error(request, 'Eror! try again')
    form = CommentForm()
    comments = Comment.objects.filter(post=post.id, is_approved=True)
    next_post = Post.objects.filter(status=True, id__gt=post.id).order_by('id').first()
    prev_post = Post.objects.filter(status=True, id__lt=post.id).order_by('-id').first()
    context = {'post':post, 'next_post':next_post ,'prev_post':prev_post, 'comments':comments, 'form':form}
    return render(request, 'single-post.html', context)


def about(request):
    return render(request, 'about.html')


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your message has been sent successfully!')
        else:
            messages.error(request, 'Please fill in all required fields before sending.')

    form = ContactForm()
    context = {'form':form}
    return render(request, 'contact.html', context)


def category(request, author=None, category=None):
    posts = Post.objects.filter(status=True)
    categories = Category.objects.all()
    
    if author:
        posts = posts.filter(author__name = author)
    if category:
        posts = posts.filter(category__name = category)

    posts = Paginator(posts, 3)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    context = {'posts':posts, 'categories':categories}
    return render(request, 'category.html', context)


def search(request):
    posts = Post.objects.filter(status=True)
    if request.method == 'GET':
        if s := request.GET.get('s'):
            posts = posts.filter(title__icontains=s)
    context = {'posts':posts}
    return render(request, 'index.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="en">

<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>Audio Post - Calvin</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!-- script
    ================================================== -->
    <script src="{% static 'js/modernizr.js ' %}"></script>
    <script defer src="{% static 'js/fontawesome/all.min.js ' %}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.pn' %}g">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.pn' %}g">
    <link rel="manifest" href="{% static 'site.webmanifest' %}">

</head>

<body id="top">


    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader"></div>
    </div>


    <!-- header
    ================================================== -->
    <header class="s-header s-header--opaque">

        <div class="s-header__logo">
            <a class="logo" href="{% url 'pages:index' %}">
                <img src="{% static 'images/logo.svg' %}" alt="Homepage">
            </a>
        </div>

        <div class="row s-header__navigation">

            <nav class="s-header__nav-wrap">

                <h3 class="s-header__nav-heading h6">Navigate to</h3>

                <ul class="s-header__nav">
                    <li><a href="{% url 'pages:index' %}" title="">Home</a></li>
                    <li><a href="{% url 'pages:about' %}" title="">About</a></li>
                    <li><a href="{% url 'pages:contact' %}" title="">Contact</a></li>
                </ul> <!-- end s-header__nav -->

                <a href="#0" title="Close Menu" class="s-header__overlay-close close-mobile-menu">Close</a>

            </nav> <!-- end s-header__nav-wrap -->

        </div> <!-- end s-header__navigation -->

        <a class="s-header__toggle-menu" href="#0" title="Menu"><span>Menu</span></a>

        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

        <div class="s-header__search">

            <div class="s-header__search-inner">
                <div class="row wide">

                    <form role="search" method="get" class="s-header__search-form" action="{% url 'pages:search' %}">
                        {% csrf_token %}
                        <label>
                            <span class="h-screen-reader-text">Search for:</span>
                            <input type="search" class="s-header__search-field" placeholder="Search for..." name="s"
                                title="Search for:" autocomplete="off">
                        </label>
                        <input type="submit" class="s-header__search-submit" value="Search">
                    </form>

                    <a href="{{ redirect_to_url }}" title="Close Search" class="s-header__overlay-close">Close</a>

                </div> <!-- end row -->
            </div> <!-- s-header__search-inner -->

        </div> <!-- end s-header__search wrap -->

        <a class="s-header__search-trigger" href="{% url 'pages:index' %}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 17.982 17.983">
                <path fill="#010101"
                    d="M12.622 13.611l-.209.163A7.607 7.607 0 017.7 15.399C3.454 15.399 0 11.945 0 7.7 0 3.454 3.454 0 7.7 0c4.245 0 7.699 3.454 7.699 7.7a7.613 7.613 0 01-1.626 4.714l-.163.209 4.372 4.371-.989.989-4.371-4.372zM7.7 1.399a6.307 6.307 0 00-6.3 6.3A6.307 6.307 0 007.7 14c3.473 0 6.3-2.827 6.3-6.3a6.308 6.308 0 00-6.3-6.301z" />
            </svg>
        </a>

    </header> <!-- end s-header -->

    {% block content %}

    {% endblock %}
    <!-- footer
    ================================================== -->
    <footer class="s-footer">

        <div class="s-footer__main">

            <div class="row">

                <div class="column large-3 medium-6 tab-12 s-footer__info">

                    <h5>About Our Site</h5>

                    <p>
                        Lorem ipsum Ut velit dolor Ut labore id fugiat in ut
                        fugiat nostrud qui in dolore commodo eu magna Duis
                        cillum dolor officia esse mollit proident Excepteur
                        exercitation nulla. Lorem ipsum In reprehenderit
                        commodo aliqua irure.
                    </p>

                </div> <!-- end s-footer__info -->

                <div class="column large-2 medium-3 tab-6 s-footer__site-links">

                    <h5>Site Links</h5>

                    <ul>
                        <li><a href="#0">About Us</a></li>
                        <li><a href="#0">Blog</a></li>
                        <li><a href="#0">FAQ</a></li>
                        <li><a href="#0">Terms</a></li>
                        <li><a href="#0">Privacy Policy</a></li>
                    </ul>

                </div> <!-- end s-footer__site-links -->

                <div class="column large-2 medium-3 tab-6 s-footer__social-links">

                    <h5>Follow Us</h5>

                    <ul>
                        <li><a href="#0">Twitter</a></li>
                        <li><a href="#0">Facebook</a></li>
                        <li><a href="#0">Dribbble</a></li>
                        <li><a href="#0">Pinterest</a></li>
                        <li><a href="#0">Instagram</a></li>
                    </ul>

                </div> <!-- end s-footer__social links -->

                <div class="column large-3 medium-6 tab-12 s-footer__subscribe">

                    <h5>Sign Up for Newsletter</h5>

                    <p>Signup to get updates on articles, interviews and events.</p>

                    <div class="subscribe-form">

                        <form id="mc-form" class="group" novalidate="true">

                            <input type="email" value="" name="dEmail" class="email" id="mc-email"
                                placeholder="Your Email Address" required="">

                            <input type="submit" name="subscribe" value="subscribe">

                            <label for="mc-email" class="subscribe-message"></label>

                        </form>

                    </div>

                </div> <!-- end s-footer__subscribe -->

            </div> <!-- end row -->

        </div> <!-- end s-footer__main -->

        <div class="s-footer__bottom">
            <div class="row">
                <div class="column">
                    <div class="ss-copyright">
                        <span>© Copyright Calvin 2020</span>
                        <span>Design by <a href="https://www.styleshout.com/">StyleShout</a></span>
                    </div> <!-- end ss-copyright -->
                </div>
            </div>

            <div class="ss-go-top">
                <a class="smoothscroll" title="Back to Top" href="#top">
                    <svg viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" width="15" height="15">
                        <path
                            d="M7.5 1.5l.354-.354L7.5.793l-.354.353.354.354zm-.354.354l4 4 .708-.708-4-4-.708.708zm0-.708l-4 4 .708.708 4-4-.708-.708zM7 1.5V14h1V1.5H7z"
                            fill="currentColor"></path>
                    </svg>
                </a>
            </div> <!-- end ss-go-top -->
        </div> <!-- end s-footer__bottom -->

    </footer> <!-- end s-footer -->


    <!-- Java Script
    ================================================== -->
    <script src="{% static 'js/jquery-3.5.0.min.js ' %}"></script>
    <script src="{% static 'js/plugins.js ' %}"></script>
    <script src="{% static 'js/main.js ' %}"></script>

</body>

</html>

templates/category.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="en">

<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>Audio Post - Calvin</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!-- script
    ================================================== -->
    <script src="{% static 'js/modernizr.js ' %}"></script>
    <script defer src="{% static 'js/fontawesome/all.min.js ' %}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.pn' %}g">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.pn' %}g">
    <link rel="manifest" href="{% static 'site.webmanifest' %}">

</head>

<body id="top">


    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader"></div>
    </div>


    <!-- header
    ================================================== -->
    <header class="s-header s-header--opaque">

        <div class="s-header__logo">
            <a class="logo" href="{% url 'pages:index' %}">
                <img src="{% static 'images/logo.svg' %}" alt="Homepage">
            </a>
        </div>

        <div class="row s-header__navigation">

            <nav class="s-header__nav-wrap">

                <h3 class="s-header__nav-heading h6">Navigate to</h3>

                <ul class="s-header__nav">
                    <li><a href="{% url 'pages:index' %}" title="">Home</a></li>
                    <li class="has-children">
                        <a href="#0" title="">Categories</a>
                        <ul class="sub-menu">
                        {% for cat in categories %}
                            <li><a href="{% url 'pages:category' cat.name %}">{{cat.name}}</a></li>
                        {% endfor %}
                        </ul>
                    </li>
                    <li><a href="{% url 'pages:about' %}" title="">About</a></li>
                    <li><a href="{% url 'pages:contact' %}" title="">Contact</a></li>
                </ul> <!-- end s-header__nav -->

                <a href="#0" title="Close Menu" class="s-header__overlay-close close-mobile-menu">Close</a>

            </nav> <!-- end s-header__nav-wrap -->

        </div> <!-- end s-header__navigation -->

        <a class="s-header__toggle-menu" href="#0" title="Menu"><span>Menu</span></a>

        <div class="s-header__search">

            <div class="s-header__search-inner">
                <div class="row wide">

                    <form role="search" method="get" class="s-header__search-form" action="{% url 'pages:search' %}">
                        {% csrf_token %}
                        <label>
                            <span class="h-screen-reader-text">Search for:</span>
                            <input type="search" class="s-header__search-field" placeholder="Search for..." name="s"
                                title="Search for:" autocomplete="off">
                        </label>
                        <input type="submit" class="s-header__search-submit" value="Search">
                    </form>

                    <a href="{{ redirect_to_url }}" title="Close Search" class="s-header__overlay-close">Close</a>

                </div> <!-- end row -->
            </div> <!-- s-header__search-inner -->

        </div> <!-- end s-header__search wrap -->

        <a class="s-header__search-trigger" href="{% url 'pages:index' %}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 17.982 17.983">
                <path fill="#010101"
                    d="M12.622 13.611l-.209.163A7.607 7.607 0 017.7 15.399C3.454 15.399 0 11.945 0 7.7 0 3.454 3.454 0 7.7 0c4.245 0 7.699 3.454 7.699 7.7a7.613 7.613 0 01-1.626 4.714l-.163.209 4.372 4.371-.989.989-4.371-4.372zM7.7 1.399a6.307 6.307 0 00-6.3 6.3A6.307 6.307 0 007.7 14c3.473 0 6.3-2.827 6.3-6.3a6.308 6.308 0 00-6.3-6.301z" />
            </svg>
        </a>

    </header> <!-- end s-header -->
    <!-- content
    ================================================== -->
    <section class="s-content">


        <!-- page header
        ================================================== -->
        <div class="s-pageheader">
            <div class="row">
                <div class="column large-12">
                    <h1 class="page-title">
                        <span class="page-title__small-type">Category</span>
                    </h1>
                </div>
            </div>
        </div> <!-- end s-pageheader-->


        <!-- masonry
        ================================================== -->
        <div class="s-bricks s-bricks--half-top-padding">

            <div class="masonry">
                <div class="bricks-wrapper h-group">

                    <div class="grid-sizer"></div>

                    <div class="lines">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                    {% for post in posts %}
                    <article class="brick entry" data-aos="fade-up">

                        <div class="entry__thumb">
                            <a href="{% url 'pages:single_post' post.id %}" class="thumb-link">
                                <img src="{% static 'images/thumbs/masonry/macbook-600.jpg' %}"
                                    srcset="{% static 'images/thumbs/masonry/macbook-600.jpg' %} 1x, {% static 'images/thumbs/masonry/macbook-1200.jpg' %} 2x"
                                    alt="">
                            </a>
                        </div> <!-- end entry__thumb -->

                        <div class="entry__text">
                            <div class="entry__header">
                                <h1 class="entry__title"><a
                                        href="{% url 'pages:single_post' post.id %}">{{post.title}}</a></h1>

                                <div class="entry__meta">
                                    <span class="byline">By:
                                        <span class='author'>
                                            <a href=" {% url 'pages:author' post.author.name %}">{{post.author}}</a>
                                        </span>
                                    </span>
                                    <span class="cat-links">
                                        {% for cat in post.category.all %}
                                        <a href="{% url 'pages:category' cat.name %}">{{cat.name}}</a>
                                        {% endfor %}
                                    </span>
                                </div>
                            </div>
                            <div class="entry__excerpt">
                                <p>
                                    {{post.description|striptags|truncatewords:30}}
                                </p>
                            </div>
                            <a class="entry__more-link" href="{% url 'pages:single_post' post.id %}">Learn More</a>
                        </div> <!-- end entry__text -->

                    </article> <!-- end article -->
                    {% endfor %}
                </div> <!-- end brick-wrapper -->

            </div> <!-- end masonry -->

            <div class="row">
                <div class="column large-12">

                    <nav class="pgn">
                        <ul>
                            {% if posts.has_previous %}
                            <li>
                                <a class="pgn__prev" href="?page={{ posts.previous_page_number }}">
                                    Prev
                                </a>
                            </li>
                            {% endif %}

                            {% for i in posts.paginator.page_range %}
                            {% if posts.number == i %}
                            <li><span class="pgn__num current">
                                    {{ i }}
                                </span></li>
                            {% else %}
                            <li><span class="pgn__num">
                                    {{ i }}
                                </span></li>
                            {% endif %}
                            {% endfor %}
                            {% if posts.has_next %}
                            <li>
                                <a class="pgn__next" href="?page={{ posts.next_page_number }}">
                                    Next
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav> <!-- end pgn -->
                </div> <!-- end column -->
            </div> <!-- end row -->

        </div> <!-- end s-bricks -->

    </section> <!-- end s-content -->
    <!-- footer
    ================================================== -->
    <footer class="s-footer">

        <div class="s-footer__main">

            <div class="row">

                <div class="column large-3 medium-6 tab-12 s-footer__info">

                    <h5>About Our Site</h5>

                    <p>
                        Lorem ipsum Ut velit dolor Ut labore id fugiat in ut
                        fugiat nostrud qui in dolore commodo eu magna Duis
                        cillum dolor officia esse mollit proident Excepteur
                        exercitation nulla. Lorem ipsum In reprehenderit
                        commodo aliqua irure.
                    </p>

                </div> <!-- end s-footer__info -->

                <div class="column large-2 medium-3 tab-6 s-footer__site-links">

                    <h5>Site Links</h5>

                    <ul>
                        <li><a href="#0">About Us</a></li>
                        <li><a href="#0">Blog</a></li>
                        <li><a href="#0">FAQ</a></li>
                        <li><a href="#0">Terms</a></li>
                        <li><a href="#0">Privacy Policy</a></li>
                    </ul>

                </div> <!-- end s-footer__site-links -->

                <div class="column large-2 medium-3 tab-6 s-footer__social-links">

                    <h5>Follow Us</h5>

                    <ul>
                        <li><a href="#0">Twitter</a></li>
                        <li><a href="#0">Facebook</a></li>
                        <li><a href="#0">Dribbble</a></li>
                        <li><a href="#0">Pinterest</a></li>
                        <li><a href="#0">Instagram</a></li>
                    </ul>

                </div> <!-- end s-footer__social links -->

                <div class="column large-3 medium-6 tab-12 s-footer__subscribe">

                    <h5>Sign Up for Newsletter</h5>

                    <p>Signup to get updates on articles, interviews and events.</p>

                    <div class="subscribe-form">

                        <form id="mc-form" class="group" novalidate="true">

                            <input type="email" value="" name="dEmail" class="email" id="mc-email"
                                placeholder="Your Email Address" required="">

                            <input type="submit" name="subscribe" value="subscribe">

                            <label for="mc-email" class="subscribe-message"></label>

                        </form>

                    </div>

                </div> <!-- end s-footer__subscribe -->

            </div> <!-- end row -->

        </div> <!-- end s-footer__main -->

        <div class="s-footer__bottom">
            <div class="row">
                <div class="column">
                    <div class="ss-copyright">
                        <span>© Copyright Calvin 2020</span>
                        <span>Design by <a href="https://www.styleshout.com/">StyleShout</a></span>
                    </div> <!-- end ss-copyright -->
                </div>
            </div>

            <div class="ss-go-top">
                <a class="smoothscroll" title="Back to Top" href="#top">
                    <svg viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" width="15" height="15">
                        <path
                            d="M7.5 1.5l.354-.354L7.5.793l-.354.353.354.354zm-.354.354l4 4 .708-.708-4-4-.708.708zm0-.708l-4 4 .708.708 4-4-.708-.708zM7 1.5V14h1V1.5H7z"
                            fill="currentColor"></path>
                    </svg>
                </a>
            </div> <!-- end ss-go-top -->
        </div> <!-- end s-footer__bottom -->

    </footer> <!-- end s-footer -->


    <!-- Java Script
    ================================================== -->
    <script src="{% static 'js/jquery-3.5.0.min.js ' %}"></script>
    <script src="{% static 'js/plugins.js ' %}"></script>
    <script src="{% static 'js/main.js ' %}"></script>

</body>

</html>

templates/lates-post.html
{% for post in posts %}
<div class="row s-hero__slide-content animate-this">
    <div class="column">
        <div class="s-hero__slide-meta">

            <span class="byline">
                Posted by
                <span class="author">
                    <a href="{% url 'pages:author' post.author.name %}">{{post.author}}</a>
                </span>
            </span>
        </div>
        <h1 class="s-hero__slide-text">
            <a href="{% url 'pages:single_post' post.id %}">
                {{post.title}}
            </a>
        </h1>
    </div>
</div>
{% endfor %}